# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def AssessCredibility(self, post_text: str,author_info: str,engagement: str,knowledge_context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.CredibilityAssessment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AssessCredibility(post_text=post_text,author_info=author_info,engagement=engagement,knowledge_context=knowledge_context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AssessCredibility", args={
                "post_text": post_text,"author_info": author_info,"engagement": engagement,"knowledge_context": knowledge_context,
            })
            return typing.cast(types.CredibilityAssessment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DetectMisinformation(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MisinformationAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DetectMisinformation(text=text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DetectMisinformation", args={
                "text": text,
            })
            return typing.cast(types.MisinformationAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractEntities(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractEntities(text=text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractEntities", args={
                "text": text,
            })
            return typing.cast(typing.List[str], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateRecommendations(self, query: str,timeline: typing.Optional["types.Timeline"] = None,user_session: typing.Optional[typing.List["types.SessionMemory"]] = None,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Recommendation"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateRecommendations(query=query,timeline=timeline,user_session=user_session,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateRecommendations", args={
                "query": query,"timeline": timeline,"user_session": user_session,
            })
            return typing.cast(typing.List["types.Recommendation"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateTimeline(self, query: str,retrieved_context: str,num_events: int,
        baml_options: BamlCallOptions = {},
    ) -> types.Timeline:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateTimeline(query=query,retrieved_context=retrieved_context,num_events=num_events,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateTimeline", args={
                "query": query,"retrieved_context": retrieved_context,"num_events": num_events,
            })
            return typing.cast(types.Timeline, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ProcessQuery(self, original_query: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.ProcessedQuery:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ProcessQuery(original_query=original_query,context=context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ProcessQuery", args={
                "original_query": original_query,"context": context,
            })
            return typing.cast(types.ProcessedQuery, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SimpleTest(self, 
        baml_options: BamlCallOptions = {},
    ) -> types.SimpleEvent:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SimpleTest(
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SimpleTest", args={
                
            })
            return typing.cast(types.SimpleEvent, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AssessCredibility(self, post_text: str,author_info: str,engagement: str,knowledge_context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CredibilityAssessment, types.CredibilityAssessment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AssessCredibility", args={
            "post_text": post_text,"author_info": author_info,"engagement": engagement,"knowledge_context": knowledge_context,
        })
        return baml_py.BamlStream[stream_types.CredibilityAssessment, types.CredibilityAssessment](
          __result__,
          lambda x: typing.cast(stream_types.CredibilityAssessment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CredibilityAssessment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DetectMisinformation(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.MisinformationAnalysis, types.MisinformationAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DetectMisinformation", args={
            "text": text,
        })
        return baml_py.BamlStream[stream_types.MisinformationAnalysis, types.MisinformationAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.MisinformationAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MisinformationAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractEntities(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List[str], typing.List[str]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractEntities", args={
            "text": text,
        })
        return baml_py.BamlStream[typing.List[str], typing.List[str]](
          __result__,
          lambda x: typing.cast(typing.List[str], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List[str], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateRecommendations(self, query: str,timeline: typing.Optional["types.Timeline"] = None,user_session: typing.Optional[typing.List["types.SessionMemory"]] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.Recommendation"], typing.List["types.Recommendation"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateRecommendations", args={
            "query": query,"timeline": timeline,"user_session": user_session,
        })
        return baml_py.BamlStream[typing.List["stream_types.Recommendation"], typing.List["types.Recommendation"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.Recommendation"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.Recommendation"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateTimeline(self, query: str,retrieved_context: str,num_events: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Timeline, types.Timeline]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateTimeline", args={
            "query": query,"retrieved_context": retrieved_context,"num_events": num_events,
        })
        return baml_py.BamlStream[stream_types.Timeline, types.Timeline](
          __result__,
          lambda x: typing.cast(stream_types.Timeline, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Timeline, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ProcessQuery(self, original_query: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ProcessedQuery, types.ProcessedQuery]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ProcessQuery", args={
            "original_query": original_query,"context": context,
        })
        return baml_py.BamlStream[stream_types.ProcessedQuery, types.ProcessedQuery](
          __result__,
          lambda x: typing.cast(stream_types.ProcessedQuery, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ProcessedQuery, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SimpleTest(self, 
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SimpleEvent, types.SimpleEvent]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SimpleTest", args={
            
        })
        return baml_py.BamlStream[stream_types.SimpleEvent, types.SimpleEvent](
          __result__,
          lambda x: typing.cast(stream_types.SimpleEvent, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SimpleEvent, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AssessCredibility(self, post_text: str,author_info: str,engagement: str,knowledge_context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AssessCredibility", args={
            "post_text": post_text,"author_info": author_info,"engagement": engagement,"knowledge_context": knowledge_context,
        }, mode="request")
        return __result__
    async def DetectMisinformation(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectMisinformation", args={
            "text": text,
        }, mode="request")
        return __result__
    async def ExtractEntities(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractEntities", args={
            "text": text,
        }, mode="request")
        return __result__
    async def GenerateRecommendations(self, query: str,timeline: typing.Optional["types.Timeline"] = None,user_session: typing.Optional[typing.List["types.SessionMemory"]] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateRecommendations", args={
            "query": query,"timeline": timeline,"user_session": user_session,
        }, mode="request")
        return __result__
    async def GenerateTimeline(self, query: str,retrieved_context: str,num_events: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateTimeline", args={
            "query": query,"retrieved_context": retrieved_context,"num_events": num_events,
        }, mode="request")
        return __result__
    async def ProcessQuery(self, original_query: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ProcessQuery", args={
            "original_query": original_query,"context": context,
        }, mode="request")
        return __result__
    async def SimpleTest(self, 
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SimpleTest", args={
            
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AssessCredibility(self, post_text: str,author_info: str,engagement: str,knowledge_context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AssessCredibility", args={
            "post_text": post_text,"author_info": author_info,"engagement": engagement,"knowledge_context": knowledge_context,
        }, mode="stream")
        return __result__
    async def DetectMisinformation(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectMisinformation", args={
            "text": text,
        }, mode="stream")
        return __result__
    async def ExtractEntities(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractEntities", args={
            "text": text,
        }, mode="stream")
        return __result__
    async def GenerateRecommendations(self, query: str,timeline: typing.Optional["types.Timeline"] = None,user_session: typing.Optional[typing.List["types.SessionMemory"]] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateRecommendations", args={
            "query": query,"timeline": timeline,"user_session": user_session,
        }, mode="stream")
        return __result__
    async def GenerateTimeline(self, query: str,retrieved_context: str,num_events: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateTimeline", args={
            "query": query,"retrieved_context": retrieved_context,"num_events": num_events,
        }, mode="stream")
        return __result__
    async def ProcessQuery(self, original_query: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ProcessQuery", args={
            "original_query": original_query,"context": context,
        }, mode="stream")
        return __result__
    async def SimpleTest(self, 
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SimpleTest", args={
            
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))