# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AssessCredibility(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CredibilityAssessment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AssessCredibility", llm_response=llm_response, mode="request")
        return typing.cast(types.CredibilityAssessment, __result__)

    def DetectMisinformation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MisinformationAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectMisinformation", llm_response=llm_response, mode="request")
        return typing.cast(types.MisinformationAnalysis, __result__)

    def ExtractEntities(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEntities", llm_response=llm_response, mode="request")
        return typing.cast(typing.List[str], __result__)

    def GenerateFollowUpQuestions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.FollowUpQuestion"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateFollowUpQuestions", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.FollowUpQuestion"], __result__)

    def GenerateRecommendations(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Recommendation"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateRecommendations", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.Recommendation"], __result__)

    def GenerateTimeline(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Timeline:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateTimeline", llm_response=llm_response, mode="request")
        return typing.cast(types.Timeline, __result__)

    def ProcessQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ProcessedQuery:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ProcessQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.ProcessedQuery, __result__)

    def SimpleTest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SimpleEvent:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SimpleTest", llm_response=llm_response, mode="request")
        return typing.cast(types.SimpleEvent, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AssessCredibility(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CredibilityAssessment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AssessCredibility", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CredibilityAssessment, __result__)

    def DetectMisinformation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MisinformationAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectMisinformation", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MisinformationAnalysis, __result__)

    def ExtractEntities(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEntities", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List[str], __result__)

    def GenerateFollowUpQuestions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.FollowUpQuestion"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateFollowUpQuestions", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.FollowUpQuestion"], __result__)

    def GenerateRecommendations(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.Recommendation"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateRecommendations", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.Recommendation"], __result__)

    def GenerateTimeline(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Timeline:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateTimeline", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Timeline, __result__)

    def ProcessQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ProcessedQuery:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ProcessQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ProcessedQuery, __result__)

    def SimpleTest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SimpleEvent:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SimpleTest", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SimpleEvent, __result__)

    