# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (11)
# #########################################################################

class CredibilityAssessment(BaseModel):
    post_id: typing.Optional[str] = Field(default=None, description='ID of the post being assessed')
    credibility_score: typing.Optional[float] = Field(default=None, description='Overall credibility score (0.0 to 1.0)')
    factors: typing.List[str] = Field(description='Factors that influenced the score')
    reasoning: typing.Optional[str] = Field(default=None, description='Explanation for the assigned score')

class Event(BaseModel):
    timestamp: typing.Optional[str] = Field(default=None, description='ISO 8601 format timestamp of when event occurred')
    summary: typing.Optional[str] = Field(default=None, description='Brief description of event')
    sources: typing.List[str] = Field(description='List of X post IDs or URLs as sources for this event')
    media: typing.Optional[str] = Field(default=None, description='Optional image or video URL associated with event')
    credibility_score: typing.Optional[float] = Field(default=None, description='0.0 to 1.0, higher is more credible')
    verified_sources: typing.Optional[int] = Field(default=None, description='Number of sources verified against knowledge base')

class FollowUpQuestion(BaseModel):
    question: typing.Optional[str] = Field(default=None, description='A natural follow-up question to continue the conversation')
    category: typing.Optional[str] = Field(default=None, description='Category: \'deep_dive\', \'related_topic\', \'verification\', \'prediction\', \'comparison\'')
    context_hint: typing.Optional[str] = Field(default=None, description='Brief hint about what this question explores')
    priority: typing.Optional[int] = Field(default=None, description='Priority 1-5, where 1 is most relevant')

class KnowledgeFact(BaseModel):
    fact_id: typing.Optional[str] = Field(default=None, description='Unique identifier for this fact')
    statement: typing.Optional[str] = Field(default=None, description='The factual statement')
    sources: typing.List[str] = Field(description='Sources that verify this fact')
    verification_status: typing.Optional[str] = Field(default=None, description='One of: \'verified\', \'disputed\', or \'unverified\'')
    verified_at: typing.Optional[str] = Field(default=None, description='ISO timestamp when this fact was verified')

class MisinformationAnalysis(BaseModel):
    is_suspicious: typing.Optional[bool] = None
    suspicious_patterns: typing.List[str]
    risk_level: typing.Optional[str] = Field(default=None, description='low, medium, or high')
    recommendation: typing.Optional[str] = None

class ProcessedQuery(BaseModel):
    original_query: typing.Optional[str] = Field(default=None, description='The original user query')
    rewritten_query: typing.Optional[str] = Field(default=None, description='Optimized query for searching')
    entities: typing.List[str] = Field(description='Extracted entities from query')
    time_range: typing.Optional[str] = Field(default=None, description='Inferred time range if any')

class Recommendation(BaseModel):
    action: typing.Optional[str] = Field(default=None, description='Suggested action or follow-up query')
    reason: typing.Optional[str] = Field(default=None, description='Why this recommendation is being made')

class SessionMemory(BaseModel):
    session_id: typing.Optional[str] = Field(default=None, description='Unique session identifier')
    query: typing.Optional[str] = Field(default=None, description='The query that was made')
    timestamp: typing.Optional[str] = Field(default=None, description='ISO timestamp of when query was made')
    results_count: typing.Optional[int] = Field(default=None, description='Number of results returned for query')
    relevance_score: typing.Optional[float] = Field(default=None, description='Relevance score of results (0.0 to 1.0)')

class SimpleEvent(BaseModel):
    id: typing.Optional[str] = None
    summary: typing.Optional[str] = None

class Timeline(BaseModel):
    topic: typing.Optional[str] = Field(default=None, description='The topic or query this timeline addresses')
    events: typing.List["Event"] = Field(description='Chronological list of events')
    total_sources: typing.Optional[int] = Field(default=None, description='Total number of unique sources across all events')
    avg_credibility: typing.Optional[float] = Field(default=None, description='Average credibility score across all events')
    predictions: typing.Optional[typing.List[str]] = Field(default=None, description='Optional what-if predictions based on observed patterns')

class XPost(BaseModel):
    tweet_id: typing.Optional[str] = Field(default=None, description='Unique X post identifier')
    text: typing.Optional[str] = Field(default=None, description='Content of post')
    author: typing.Optional[str] = Field(default=None, description='Username of author')
    timestamp: typing.Optional[str] = Field(default=None, description='ISO timestamp when post was created')
    fave_count: typing.Optional[int] = Field(default=None, description='Number of favorites/likes')
    retweet_count: typing.Optional[int] = Field(default=None, description='Number of retweets')
    is_verified: typing.Optional[bool] = Field(default=None, description='Whether author is verified')
    media_urls: typing.List[str] = Field(description='List of media URLs (images, videos)')
    location: typing.Optional[str] = Field(default=None, description='Optional location tag')
    credibility_score: typing.Optional[float] = Field(default=None, description='Calculated credibility score (0.0 to 1.0)')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
