# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CredibilityAssessment": types.CredibilityAssessment,
    "stream_types.CredibilityAssessment": stream_types.CredibilityAssessment,

    "types.Event": types.Event,
    "stream_types.Event": stream_types.Event,

    "types.KnowledgeFact": types.KnowledgeFact,
    "stream_types.KnowledgeFact": stream_types.KnowledgeFact,

    "types.MisinformationAnalysis": types.MisinformationAnalysis,
    "stream_types.MisinformationAnalysis": stream_types.MisinformationAnalysis,

    "types.ProcessedQuery": types.ProcessedQuery,
    "stream_types.ProcessedQuery": stream_types.ProcessedQuery,

    "types.Recommendation": types.Recommendation,
    "stream_types.Recommendation": stream_types.Recommendation,

    "types.SessionMemory": types.SessionMemory,
    "stream_types.SessionMemory": stream_types.SessionMemory,

    "types.SimpleEvent": types.SimpleEvent,
    "stream_types.SimpleEvent": stream_types.SimpleEvent,

    "types.Timeline": types.Timeline,
    "stream_types.Timeline": stream_types.Timeline,

    "types.XPost": types.XPost,
    "stream_types.XPost": stream_types.XPost,


}